Fixes sre-login to use OCM_USER var
openshift/ocm-container pull request #28
Opened 2021-03-09 00:28 UTC by clcollins

Currently, the `sre-login` script ignores if the `$OCM_USER` variable is
set.  This change modifies the script to pass the `-e
${OCM_USER}@redhat.com` flag when calling `cluster-login` if the
`$OCM_USER` variable is set.

Signed-off-by: Christopher Collins <collins.christopher@gmail.com>

2021-03-15 20:24 UTC, clcollins commented
@georgettica I took this a bit further and added real argument handling so any ID could be passed as an argument, and added a help message/usage message and debug.

2021-03-15 21:39 UTC, clcollins commented
Confirmed working with automatic/`INITIAL_CLUSTER_LOGIN` as well, using ENV VARS.

2021-03-16 07:25 UTC, georgettica commented
❤️ I will test this today to verify

2021-03-16 13:33 UTC, georgettica commented
for some reason it doesn't want to work for me now (with your change or without)

if you can pull someone else to verify it works for them (macos user preferably) that would be super! as I know it's an issue you have and can be solved easily with this simple change

2021-05-10 15:26 UTC, iamkirkbater requested changes
I'm a bit confused what the addition of `OCM_IDENTITY` adds?  Also, I'm just a smidge worried about backwards compatibility with removing the positional argument and forcing that to change to a flag, is there a reason why we're moving in that direction?

2021-06-03 06:26 UTC, georgettica commented
merged a ton of PR's and this had merge conflicts

waiting for someone to review this, so I can merge it

2021-07-26 07:32 UTC, georgettica commented
@clcollins is this still required?

2021-08-10 20:43 UTC, closed without merging

2021-08-10 20:43 UTC, clcollins commented
With the backplane stuff, this is no longer necessary/useful.