WIP: add persistentImages
openshift/ocm-container pull request #281
Opened 2024-05-14 11:06 UTC by T0MASD

Add persistentImages feature which perserves local images between ocm-container sessions

2024-05-14 16:42 UTC, T0MASD commented
/hold for fix to left over containers
```
$ podman ps -aq
bd2a8b53fd5c
e8bfe9d90987
```

2024-05-14 18:28 UTC, T0MASD commented
/unhold it's not possible to mount just  /var/lib/containers/storage/overlay/ in addition verified 2 container sessions happily share the mount

2024-05-14 18:29 UTC, T0MASD commented
/unhold

2024-05-14 18:37 UTC, clcollins requested changes
This looks great!  Other than the ocm client comment and a suggestion for a debug log line, I'm good with this.

I see you have this held related to container cleanup?  What is the issue you're seeing there?

2024-05-14 18:37 UTC, clcollins commented on pkg/featureSet/persistentImages/persistentImages.go
> +	mount := filepath.Join(home, sourceDir)
```suggestion
	log.Debug("using image cache mount: " + mount)
	mount := filepath.Join(home, sourceDir)
```

Not a deal breaker at all - just suggesting some debug logging for troubleshooting.

2024-05-14 18:37 UTC, clcollins commented on pkg/featureSet/persistentImages/persistentImages.go
> +	"github.com/openshift/ocm-container/pkg/engine"
```suggestion
	"github.com/openshift/ocm-container/pkg/engine"
	log "github.com/sirupsen/logrus"
```

Related to the debug log comment below...

2024-05-14 20:08 UTC, T0MASD commented on pkg/featureSet/persistentImages/persistentImages.go
> +	ocmClient, err := ocm.NewClient()
good catch, it's from copy/pasta, removed in 191364e55b09332620264c71b3ba1387fa44f6ba

2024-05-14 20:09 UTC, T0MASD commented
/label tide/merge-method-squash

2024-05-15 17:36 UTC, clcollins commented
/lgtm

2024-05-15 17:46 UTC, merged